import { useEffect, useMemo, useState } from 'react'
import { Headphones, Mic, NotebookPen, Pencil, Plus, Search, Sparkles, Trash2, X } from 'lucide-react'
import { adminApi } from '../lib/adminApi'
import { AdminSelect } from './AdminPage'

type Status = 'draft' | 'published' | 'locked' | 'no_content'
type Skill = 'vocabulary_grammar' | 'dictation' | 'shadowing' | 'review'
type Textbook = { id: string; title_ko: string }
type Lesson = { id: string; textbook_id: string; lesson_number: number; title_ko: string; textbooks?: { title_ko?: string } }
type Exercise = { id: string; lesson_id: string; skill_type: Skill; exercise_type: string; prompt_ko: string; prompt_vi?: string | null; answer?: unknown; explanation_vi?: string | null; media_url?: string | null; sort_order: number; status: Status; lessons?: Lesson & { textbooks?: { title_ko?: string } } }

const skills = [
  { value: 'vocabulary_grammar', label: 'Từ vựng & Ngữ pháp', icon: NotebookPen },
  { value: 'dictation', label: 'Nghe chép chính tả', icon: Headphones },
  { value: 'shadowing', label: 'Shadowing', icon: Mic },
  { value: 'review', label: 'Ôn tập', icon: Sparkles },
] as const
const statuses = [{ value: 'draft', label: 'Bản nháp' }, { value: 'published', label: 'Đã xuất bản' }, { value: 'locked', label: 'Đã khóa' }, { value: 'no_content', label: 'Chưa có nội dung' }]
const emptyDraft = { lessonId: '', skillType: 'vocabulary_grammar', exerciseType: 'question', promptKo: '', promptVi: '', answer: '', explanationVi: '', mediaUrl: '', sortOrder: '0', status: 'draft' }

export default function AdminExercises() {
  const [textbooks, setTextbooks] = useState<Textbook[]>([]), [lessons, setLessons] = useState<Lesson[]>([]), [items, setItems] = useState<Exercise[]>([])
  const [book, setBook] = useState('all'), [lesson, setLesson] = useState('all'), [skill, setSkill] = useState('all'), [search, setSearch] = useState('')
  const [editing, setEditing] = useState<Exercise | null | undefined>(undefined), [draft, setDraft] = useState<Record<string, string>>(emptyDraft), [error, setError] = useState(''), [saving, setSaving] = useState(false)
  const load = async () => { try { const [b, l, e] = await Promise.all([adminApi<Textbook[]>('/textbooks'), adminApi<Lesson[]>('/lessons'), adminApi<Exercise[]>('/exercises')]); setTextbooks(b); setLessons(l); setItems(e) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể tải bài tập.') } }
  useEffect(() => { void load() }, [])
  const availableLessons = useMemo(() => lessons.filter((item) => book === 'all' || item.textbook_id === book), [book, lessons])
  const filtered = items.filter((item) => (book === 'all' || item.lessons?.textbook_id === book) && (lesson === 'all' || item.lesson_id === lesson) && (skill === 'all' || item.skill_type === skill) && `${item.prompt_ko} ${item.prompt_vi || ''} ${item.lessons?.title_ko || ''}`.toLowerCase().includes(search.trim().toLowerCase()))
  const open = (item?: Exercise) => { setEditing(item || null); setDraft(item ? { lessonId: item.lesson_id, skillType: item.skill_type, exerciseType: item.exercise_type, promptKo: item.prompt_ko, promptVi: item.prompt_vi || '', answer: typeof item.answer === 'string' ? item.answer : JSON.stringify(item.answer || {}), explanationVi: item.explanation_vi || '', mediaUrl: item.media_url || '', sortOrder: String(item.sort_order), status: item.status } : { ...emptyDraft, lessonId: availableLessons[0]?.id || lessons[0]?.id || '' }) }
  const save = async () => { if (!draft.lessonId || !draft.promptKo.trim()) return setError('Vui lòng chọn bài học và nhập nội dung bài tập.'); setSaving(true); try { let answer: unknown = draft.answer; try { answer = draft.answer ? JSON.parse(draft.answer) : {} } catch {} const body = { ...draft, answer, sortOrder: Number(draft.sortOrder) || 0 }; await adminApi(`/exercises${editing?.id ? `/${editing.id}` : ''}`, { method: editing?.id ? 'PATCH' : 'POST', body: JSON.stringify(body) }); setEditing(undefined); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể lưu bài tập.') } finally { setSaving(false) } }
  const remove = async (item: Exercise) => { if (!confirm(`Xóa bài tập “${item.prompt_ko}”?`)) return; try { await adminApi(`/exercises/${item.id}`, { method: 'DELETE' }); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể xóa bài tập.') } }
  return <div className="admin-exercises">
    <div className="admin-panel-title"><div><h2>Bài tập theo kỹ năng</h2><p>Mỗi nội dung được gắn với đúng giáo trình, bài học và một trong bốn kỹ năng.</p></div><button className="admin-primary" onClick={() => open()}><Plus size={18}/> Thêm bài tập</button></div>
    {error && <div className="admin-error">{error}<button onClick={() => setError('')}><X size={18}/></button></div>}
    <div className="admin-toolbar admin-toolbar-with-filters"><label><Search size={18}/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Tìm nội dung bài tập…"/></label><div className="admin-filter-controls"><AdminSelect value={book} options={[{ value:'all',label:'Tất cả giáo trình'},...textbooks.map((x)=>({value:x.id,label:x.title_ko}))]} onChange={(v)=>{setBook(v);setLesson('all')}}/><AdminSelect value={lesson} options={[{value:'all',label:'Tất cả bài học'},...availableLessons.map((x)=>({value:x.id,label:`Bài ${x.lesson_number} · ${x.title_ko}`}))]} onChange={setLesson}/><AdminSelect value={skill} options={[{value:'all',label:'Tất cả kỹ năng'},...skills.map(({value,label})=>({value,label}))]} onChange={setSkill}/><span>{filtered.length} mục</span></div></div>
    <div className="admin-exercise-grid">{filtered.map((item)=>{const meta=skills.find((x)=>x.value===item.skill_type)!;const Icon=meta.icon;return <article key={item.id} className="admin-exercise-card"><div className="admin-exercise-head"><span><Icon size={17}/>{meta.label}</span><div><button onClick={()=>open(item)} aria-label="Sửa"><Pencil size={16}/></button><button className="danger" onClick={()=>void remove(item)} aria-label="Xóa"><Trash2 size={16}/></button></div></div><small>{item.lessons?.textbooks?.title_ko || 'Giáo trình'} · Bài {item.lessons?.lesson_number}</small><h3>{item.prompt_ko}</h3>{item.prompt_vi&&<p>{item.prompt_vi}</p>}<div className="admin-exercise-foot"><span className={`admin-status ${item.status}`}>{statuses.find((x)=>x.value===item.status)?.label}</span><em>{item.exercise_type}</em></div></article>})}</div>
    {!filtered.length && <div className="admin-empty">Chưa có bài tập phù hợp với bộ lọc.</div>}
    {editing !== undefined && <div className="admin-modal-backdrop" onMouseDown={(e)=>{if(e.target===e.currentTarget)setEditing(undefined)}}><section className="admin-modal"><header><div><span><NotebookPen size={22}/></span><div><h2>{editing ? 'Chỉnh sửa' : 'Thêm'} bài tập</h2><p>Chọn giáo trình gián tiếp qua bài học và loại kỹ năng.</p></div></div><button onClick={()=>setEditing(undefined)}><X/></button></header><div className="admin-form"><label>Giáo trình<AdminSelect value={lessons.find(x=>x.id===draft.lessonId)?.textbook_id || textbooks[0]?.id || ''} options={textbooks.map(x=>({value:x.id,label:x.title_ko}))} onChange={(v)=>setDraft({...draft,lessonId:lessons.find(x=>x.textbook_id===v)?.id||''})}/></label><label>Bài học *<AdminSelect value={draft.lessonId} options={lessons.filter(x=>x.textbook_id===(lessons.find(y=>y.id===draft.lessonId)?.textbook_id||textbooks[0]?.id)).map(x=>({value:x.id,label:`Bài ${x.lesson_number} · ${x.title_ko}`}))} onChange={(v)=>setDraft({...draft,lessonId:v})}/></label><label>Kỹ năng *<AdminSelect value={draft.skillType} options={skills.map(({value,label})=>({value,label}))} onChange={(v)=>setDraft({...draft,skillType:v})}/></label><label>Dạng bài<input value={draft.exerciseType} onChange={(e)=>setDraft({...draft,exerciseType:e.target.value})} placeholder="question, multiple_choice…"/></label><label className="wide">Nội dung tiếng Hàn *<textarea rows={3} value={draft.promptKo} onChange={(e)=>setDraft({...draft,promptKo:e.target.value})}/></label><label className="wide">Nội dung tiếng Việt<textarea rows={2} value={draft.promptVi} onChange={(e)=>setDraft({...draft,promptVi:e.target.value})}/></label><label className="wide">Đáp án (văn bản hoặc JSON)<textarea rows={3} value={draft.answer} onChange={(e)=>setDraft({...draft,answer:e.target.value})}/></label><label>URL audio/hình<input value={draft.mediaUrl} onChange={(e)=>setDraft({...draft,mediaUrl:e.target.value})}/></label><label>Thứ tự<input type="number" value={draft.sortOrder} onChange={(e)=>setDraft({...draft,sortOrder:e.target.value})}/></label><label className="wide">Giải thích<textarea rows={2} value={draft.explanationVi} onChange={(e)=>setDraft({...draft,explanationVi:e.target.value})}/></label><label className="wide">Trạng thái<AdminSelect value={draft.status} options={statuses} onChange={(v)=>setDraft({...draft,status:v})}/></label></div><footer><button className="admin-cancel" onClick={()=>setEditing(undefined)}>Hủy</button><button className="admin-primary" disabled={saving} onClick={()=>void save()}>{saving?'Đang lưu…':'Lưu bài tập'}</button></footer></section></div>}
  </div>
}
